version: "3"
services:
  anime-me-postgres-test:
    image: postgres:13-alpine
    container_name: anime-me-postgres-test
    ports:
      - 5434:${POSTGRES_PORT}
    volumes:
      - ~/data/anime-me-test/postgres-test:/var/lib/postgresql/data
    environment:
      NODE_ENV: test
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -p ${POSTGRES_PORT}
  anime-me-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: anime-me-test
    depends_on:
      - anime-me-postgres-test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    working_dir: /usr/src/anime-me-test
    command: bash -c "npm run test:migration:run && npm run test:seed && npm test"
    environment:
      NODE_ENV: test
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
volumes:
  anime-me-postgres-test:
