name: Deploy on Heroku

on:
  push:
    branches:
      - main

jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          jwt_secret: ${{secrets.JWT_SECRET}}
          branch: "main"
      - name: Migrate DB
        run: heroku run bash -c "npx prisma migrate deploy"
